version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "7654:8000"
    command:
      [
        "poetry",
        "run",
        "python",
        "src/server.py",
        "--host",
        "0.0.0.0",
        "--port",
        "7654",
      ]
