version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "src.api_main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
